name: Run Ansible Playbook

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Ansible
        run: sudo apt-get update && sudo apt-get install -y ansible
      - name: Start SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}
      - name: Run Ansible playbook
        env:
          ANSIBLE_ROLES_PATH: ansible_new/roles
        run: |
          ansible-playbook ansible_new/playbooks/main.yml \
            -i "${{ secrets.SSH_HOST }}," \
            --user ${{ secrets.SSH_USER }} \
            --ssh-extra-args "-p ${{ secrets.SSH_PORT }}"

