name: Run Ansible Playbook

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Check SSH agent
        run: ssh-add -l
      - name: Install Ansible
        run: sudo dnf install -y ansible
      - name: Start SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}
      - name: Test SSH connection
        run: ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@127.0.0.1 -p ${{ secrets.SSH_PORT }} "echo Connected!"
      - name: Run Ansible playbook
        env:
          ANSIBLE_ROLES_PATH: ansible_new/roles
        run: |
          ansible-playbook ansible_new/playbooks/main.yml \
            -i "127.0.0.1," \
            --user ${{ secrets.SSH_USER }} \
            --private-key ~/.ssh/id_ed25519 \
            --ssh-extra-args "-t -p ${{ secrets.SSH_PORT }} -o StrictHostKeyChecking=no"

